version: "3.9"

services:
  localstack:
    networks:
      - ls_network
    container_name: localstack
    image: localstack/localstack-pro:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway

    environment:
      - DEBUG=1  # enable more verbose logs
      - DOCKER_HOST=unix:///var/run/docker.sock #unix socket to communicate with the docker daemon
      - LOCALSTACK_HOST=localstack # where services are available from other containers
      - LAMBDA_DOCKER_NETWORK=ls_network
      - DISABLE_CUSTOM_CORS_APIGATEWAY=1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - EXTENSION_AUTO_INSTALL=localstack-extension-outages
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=60
      - PERSIST_ALL=false

    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  ls_network:
    name: ls_network
